export let FORM_EXAMEN_ESTADO = {
  tipo_formulario: 'mini',
  btn: 'Guardar',
  btnLimpiar: 'Limpiar',
  alertas: true,
  modelo: 'DocumentoPrograma',
  campos: [
    {
      etiqueta: 'texto',
      claseGrid: 'col-12',
      valor: 'Examen de estado',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-2',
      nombre: 'TipoExamen',
      label_i18n: 'Tipo examén',
      placeholder_i18n: 'Tipo examén',
      requerido: true,
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'SNP',
      label_i18n: 'SNP',
      placeholder_i18n: 'SNP',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'ConfirmarSNP',
      label_i18n: 'Confirmar SNP',
      placeholder_i18n: 'Confirmar SNP',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'AnioPresentacion',
      label_i18n: 'Año presentación',
      placeholder_i18n: 'Año presentación',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'fileRev',
      claseGrid: 'col-2',
      clase: 'form-control',
      nombre: 'Documento',
      label_i18n: 'Soporte',
      placeholder_i18n: 'Soporte',
      requerido: true,
      tipo: 'pdf,png,jpeg,jpg',
      tipoDocumento: 6,
      formatos: 'pdf, png, jpeg, jpg',
      url: '',
      tamanoMaximo: 2,
    },
    {
      etiqueta: 'titulo',
      claseGrid: 'col-12 mt-4',
      valor: 'Examen de estado',
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-2',
      nombre: 'TipoExamen2',
      label_i18n: 'Tipo examén', 
      placeholder_i18n: 'Tipo examén',
      requerido: false,
      opciones: [], 
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'SNP2',
      label_i18n: 'SNP', 
      placeholder_i18n: 'SNP', 
      requerido: false,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'ConfirmarSNP2',
      label_i18n: 'Confirmar SNP', 
      placeholder_i18n: 'Confirmar SNP', 
      requerido: false,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-2',
      nombre: 'AnioPresentacion2',
      label_i18n: 'Año presentación', 
      placeholder_i18n: 'Año presentación',
      requerido: false,
      tipo: 'text',
    },
    {
      etiqueta: 'fileRev',
      claseGrid: 'col-2',
      clase: 'form-control',
      nombre: 'Documento2',
      label_i18n: 'Soporte', 
      placeholder_i18n: 'Soporte',
      requerido: false,
      tipo: 'pdf,png,jpeg,jpg',
      tipoDocumento: 6,
      formatos: 'pdf, png, jpeg, jpg',
      url: '',
      tamanoMaximo: 2,
    },
  ],
};