
export let NUEVO_TERCERO = {
  // titulo: 'FormacionAcademica',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  btnLimpiar: false,
  modelo: 'Tercero',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: '',
      nombre: 'Nit',
      label_i18n: 'nit',
      placeholder_i18n: 'nit',
      requerido: true,
      deshabilitar: false,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: '',
      nombre: 'NombreCompleto',
      label_i18n: 'nombre_entidad',
      placeholder_i18n: 'nombre_entidad',
      requerido: true,
      tipo: 'InfoPersona',
      key: 'NombreCompleto',
      opciones: [],
      entrelazado: true,
    },
    {
      etiqueta: 'select',
      claseGrid: '',
      nombre: 'Pais',
      label_i18n: 'pais_entidad',
      placeholder_i18n: 'pais_entidad',
      requerido: true,
      tipo: 'Lugar',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: '',
      nombre: 'TipoTrecero',
      label_i18n: 'tipo_tercero',
      placeholder_i18n: 'tipo_tercero',
      requerido: true,
      tipo: 'TipoTercero',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'input',
      claseGrid: '',
      nombre: 'Correo',
      label_i18n: 'correo_entidad',
      placeholder_i18n: 'correo_entidad',
      requerido: true,
      tipo: 'email',
    },
    {
      etiqueta: 'input',
      claseGrid: '',
      nombre: 'Telefono',
      label_i18n: 'telefono_entidad',
      placeholder_i18n: 'telefono_entidad',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: '',
      nombre: 'Direccion',
      label_i18n: 'direccion_entidad',
      placeholder_i18n: 'direccion_entidad',
      requerido: true,
      tipo: 'text',
    },
  ],
}
